server:
  port: 8083

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.pm.analyticservice.kafka.UserEvent
        spring.json.trusted.packages: "*"
  application:
    name: analytic-service

     # properties:
    #    spring.json.use.type.headers: false
    #    spring.json.value.default.type: com.pm.analyticservice.kafka
     #   spring.json.trusted.packages: "*"
   # bootstrap-servers: kafka:9092
    #  auto-offset-reset: earliest

